version: "3"

services:

  web:
    container_name: web-server
    image: tpilvelis/web-server:v0.0.1
    ports:
      - "80:80"
    networks:
      - webnet

  solver_service:
    container_name: solver-service
    image: tpilvelis/solver-service:v0.0.1
    ports:
      - "5000:5000"
    networks:
      - webnet

  validator_service:
    container_name: validator-service
    image: tpilvelis/validator-service:v0.0.1
    ports:
      - "5001:5001"
    networks:
      - webnet

  generate_service:
    container_name: generate-service
    image: tpilvelis/generate-service:v0.0.1
    ports:
      - "5002:5002"
    networks:
      - webnet

#  bot_service:
#    container_name: bot-service
#    image: tpilvelis/bot-service:v0.0.1
#    ports:
#      - "5002:5002"
#    networks:
#      - webnet

networks:
  webnet: