version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tpilvelis/solver_service:v0.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:5000"
    networks:
      - webnet
networks:
  webnet: